### ISSUE TITLE
Is it necessary to use setState function to modify state values?

### ISSUE THREAD

**Issue by ntubiolin** [Yoctol/agricola-score#3]
Hi! Thank you for providing such a good bottender example.
I have problems when reading some state-changing code like the one below:
https://github.com/Yoctol/agricola-score/blob/fdf79287cc7e46d687aeb2a2064aa8e024b9b944/src/form.js#L34
According to the official [bottender doc](https://bottender.js.org/docs/en/the-basics-session#adding-state-to-the-conversation), it says that
> Note: don't modify state directly using this.state.stateKey = stateValue;, it may cause unexpected behavior in the future.

I am wondering is it necessary to use setState function to modify state values? For example, `context.setState({form: {
    ...context.form,
    inForm: true,
  },})`.

**Comment by etrex** [comment]
Hi ntubiolin,

Thank you for pointing out that this project is inconsistent with the document.

We recommend that you use `setState` to modify state values.

`setState` is the unique public API the Bottender provided.

we may use this API to extend more possibilities.

We do not guarantee that direct assign will work in the future.

If you want to build a conversational form in Bottender, please refer to this document: https://github.com/Yoctol/bottender-proposal-conversation.

That is our latest design for conversation.

I will rewrite this project with `bottender-proposal-conversation`.
